language: node_js
node_js: 
 - "6"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=jdiegoisaza -Dsonar.projectKey=jdiegoisaza_micalc -Dsonar.sources='./app' -X
after_success:
 - npm run coveralls